#!/bin/bash

# Setup Deployment Workflow Script
# This script helps configure Railway projects for proper staging/production workflow

echo "🚀 Setting up Deployment Workflow"
echo "=================================="
echo ""

echo "📋 Current Railway Projects:"
echo "1. awake-surprise (Production)"
echo "2. disciplined-presence (Staging)"
echo ""

echo "🎯 Recommended Configuration:"
echo "Production (awake-surprise):"
echo "  - Branch: main"
echo "  - Auto-deploy: ✅ Enabled"
echo "  - Environment: production"
echo ""
echo "Staging (disciplined-presence):"
echo "  - Branch: develop"
echo "  - Auto-deploy: ✅ Enabled"
echo "  - Environment: staging"
echo ""

echo "📝 Manual Steps Required:"
echo "========================="
echo ""
echo "1. Configure Staging Project (disciplined-presence):"
echo "   - Go to Railway Dashboard"
echo "   - Select 'disciplined-presence' project"
echo "   - Go to Settings → Source"
echo "   - Set branch to 'develop'"
echo "   - Enable auto-deploy"
echo ""
echo "2. Configure Production Project (awake-surprise):"
echo "   - Go to Railway Dashboard"
echo "   - Select 'awake-surprise' project"
echo "   - Go to Settings → Source"
echo "   - Set branch to 'main'"
echo "   - Enable auto-deploy"
echo ""
echo "3. Verify Environment Variables:"
echo "   - Staging should use staging-specific URLs"
echo "   - Production should use production URLs"
echo "   - Never mix staging and production databases"
echo ""

echo "✅ After Configuration:"
echo "======================"
echo ""
echo "Workflow will be:"
echo "1. Feature development → develop branch"
echo "2. Auto-deploy to staging"
echo "3. Test on staging"
echo "4. Merge to main → Auto-deploy to production"
echo ""

echo "🔗 Useful Links:"
echo "================"
echo "- Railway Dashboard: https://railway.app"
echo "- Production URL: https://app.savionray.com"
echo "- Staging URL: (check Railway dashboard for disciplined-presence project)"
echo ""

echo "📚 Documentation:"
echo "================="
echo "- See DEPLOYMENT_WORKFLOW.md for detailed instructions"
echo "- See ENVIRONMENT_SEPARATION_GUIDE.md for environment setup"
echo ""

echo "🎉 Setup complete! Follow the manual steps above to configure Railway projects."
